channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=2.0.1
  - numpy=1.18
  - pandas=1.0
  - pyarrow=0.15.1
  - scipy=1.4
  - pyyaml=5.3
  - jupyterlab=2.1
  - jupyter-server-proxy=1.3
  - librosa=0.7
  - appmode=0.7
  - jinja2<=2.9
  - pip
  - pip:
    - praat-parselmouth
    - git+https://github.com/rsprouse/phonlab
    - git+https://github.com/rsprouse/audiolabel
    - git+https://github.com/rsprouse/espspy

