channels:
  - conda-forge
dependencies:
  - python=3.9
  - bokeh=2.2
  - nodejs
  - numpy=1.19
  - pandas=1.1
  - pyarrow=0.17
  - scipy=1.5
  - pyyaml=5.3
  - jupyterlab=2.1
  - jupyter-server-proxy=1.3
  - librosa=0.7
  - appmode=0.1
  - jinja2<=2.10
  - wget
  - pip
  - pip:
    - praat-parselmouth
    - git+https://github.com/rsprouse/phonlab
    - git+https://github.com/rsprouse/audiolabel
    - git+https://github.com/rsprouse/espspy
    - git+https://github.com/rsprouse/bokeh_phon

