#!/bin/bash

# This is an attempt to set EXTERNAL_URL for automatic use of
# remote_jupyter_proxy_url Python function in notebooks.
# TODO: proper detection of external url. `hostname` returns
# the proxied name, not the external name.
#export EXTERNAL_URL=`hostname`

# This is not installing properly in environment.yml.
# TODO: Remove the next line when environment.yml install works.
pip install git+https://github.com/rsprouse/bokeh_phon@936b328cca75588664a0fce2b94ca21dfb20b362

# To make sure Bokeh uses the monkeypatched version and does not
# retrieve an unaltered version from a cdn, set BOKEH_RESOURCES.
# If the need for the moneypatch to add box select to line glyphs
# is eliminated then this will no longer be required.
export BOKEH_RESOURCES=inline

exec "$@"
